### ISSUE TITLE
No internal metrics and TTFB in Riemann store

### ISSUE THREAD

**Issue by sanel** [chrissnell/crabby#25]
With this configuration:

```yaml
general:
  request-timeout: 15s
  report-internal-metrics: true
  internal-metrics-gathering-interval: 10

jobs:
  - name: site
    type: simple
    url: "https://site"
    interval: 10

storage:
  riemann:
    host: localhost
    port: 5555
    metric-namespace: crabby
```

only these metrics are present:

```
crabby.site.dns_duration
crabby.site.server_response_duration
crabby.site.tls_handshake_duration
```

No internal and TTFB metrics. What about server load, is that part of selenium type?
